version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  build:
    commands:
      - npm run build
      # Copy deployment files into build folder
      - cp appspec.yml build/
      - mkdir -p build/scripts
      - cp scripts/restart_server.sh build/scripts/

artifacts:
  files:
    - '**/*'
  base-directory: build
